@default_files = ('s05_Julmy_Sylvain.tex');

$latex = 'texfot latex -interaction=nonstopmode -file-line-error -shell-escape';
$pdflatex = 'texfot xelatex -interaction=nonstopmode -file-line-error -shell-escape';
$clean_ext = "bbl glo lol ist run.xml synctex.gz";
