ALTER TABLE paper DISABLE TRIGGER ALL;
ALTER TABLE cites DISABLE TRIGGER ALL;
ALTER TABLE author DISABLE TRIGGER ALL;
ALTER TABLE conference DISABLE TRIGGER ALL;
ALTER TABLE writes DISABLE TRIGGER ALL;
ALTER TABLE submits DISABLE TRIGGER ALL;