ALTER TABLE paper ENABLE TRIGGER ALL;
ALTER TABLE cites ENABLE TRIGGER ALL;
ALTER TABLE author ENABLE TRIGGER ALL;
ALTER TABLE conference ENABLE TRIGGER ALL;
ALTER TABLE writes ENABLE TRIGGER ALL;
ALTER TABLE submits ENABLE TRIGGER ALL;